apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-boot-app
  template:
    metadata:
      labels:
        app: spring-boot-app
    spec:
      imagePullSecrets:
      - name: ecr-secret

      containers:
      - name: spring-boot-app
        image: ECRreponame/imagename:tag
        ports:
        - containerPort: 8082
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "___"  # Or any other environment-specific settings

---
apiVersion: v1
kind: Service
metadata:
  name: spring-boot-service
spec:
  type: NodePort
  selector:
    app: spring-boot-app
  ports:
    - protocol: TCP
      port: 8082        # The port that the service will expose
      targetPort: 8082 # The port on the container that the service will forward to
      nodePort: 30001  # The port on each node that will forward traffic to the service
