apiVersion: apps/v1
kind: Deployment
metadata:
  name: temporal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: temporal
  template:
    metadata:
      labels:
        app: temporal
    spec:
      containers:
        - name: temporal
          image: temporalio/auto-setup:latest
          env:
            - name: DB
              value: "postgres12"
            - name: DB_PORT
              value: "5432"
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PWD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PWD
            - name: POSTGRES_SEEDS
              value: "postgres-service.default.svc.cluster.local"
            # Remove or comment out the following line
            # - name: DYNAMIC_CONFIG_FILE_PATH
            #   value: "/etc/temporal/config/dynamicconfig/development-sql.yaml"
          ports:
            - containerPort: 7233
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "1"
      volumes:
        - name: dynamic-config
          persistentVolumeClaim:
            claimName: temporal-config-pvc

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: temporal-config-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: temporal-config
data:
  docker.yaml: |
    # Database configuration
    database:
      host: "tcp://postgres-service.default.svc.cluster.local:5432"
      port: 5432
      user: "admin"
      password: "Inhlth123"

    # Temporal configuration
    frontend:
      rpc:
        address: "localhost:7233"

---

apiVersion: v1
kind: Service
metadata:
  name: temporal
spec:
  selector:
    app: temporal  # Ensure this matches your pod labels
  ports:
    - port: 7233           # The port that will be exposed
      targetPort: 7233     # The port on the pod
      nodePort: 30003      # The port to expose on each node
  type: NodePort
