apiVersion: apps/v1
kind: Deployment
metadata:
  name: temporal-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: temporal-ui
  template:
    metadata:
      labels:
        app: temporal-ui
    spec:
      containers:
        - name: temporal-ui
          image: temporalio/ui:latest
          env:
            - name: TEMPORAL_ADDRESS
              value: "ClusterIP:7233"  # Only the host:port, no prefix
            - name: TEMPORAL_CORS_ORIGINS
              value: "___________"  # Set CORS origin explicitly
            - name: TEMPORAL_UI_PORT
              value: "8084"  # Specify the UI port if needed
          ports:
            - containerPort: 8084
---
apiVersion: v1
kind: Service
metadata:
  name: temporal-ui
spec:
  type: NodePort
  selector:
    app: temporal-ui
  ports:
    - port: 8084
      targetPort: 8084
      nodePort: 30021  # NodePort to expose the UI
