apiVersion: v1
kind: Service
metadata:
  name: temporal
spec:
  selector:
    app: temporal  # Ensure this matches your pod labels
  ports:
    - port: 7233           # The port that will be exposed
      targetPort: 7233     # The port on the pod
      nodePort: 30003      # The port to expose on each node
  type: NodePort
[ec2-user@ip-10-0-6-37 temporal]$ cat temporal-ui-deployment.yaml 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: temporal-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: temporal-ui
  template:
    metadata:
      labels:
        app: temporal-ui
    spec:
      containers:
        - name: temporal-ui
          image: temporalio/ui:latest
          env:
            - name: TEMPORAL_ADDRESS
              value: "10.102.185.249:7233"  # Only the host:port, no prefix
            - name: TEMPORAL_CORS_ORIGINS
              value: "ec2-54-163-118-19.compute-1.amazonaws.com"  # Set CORS origin explicitly
            - name: TEMPORAL_UI_PORT
              value: "8084"  # Specify the UI port if needed
          ports:
            - containerPort: 8084
---
apiVersion: v1
kind: Service
metadata:
  name: temporal-ui
spec:
  type: NodePort
  selector:
    app: temporal-ui
  ports:
    - port: 8084
      targetPort: 8084
      nodePort: 30021  # NodePort to expose the UI
